name: Nix Build
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      nix-changed: ${{ steps.changed-nix-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get changed Nix files
        id: changed-nix-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: |
            **/*.nix
            pnpm-lock.yaml
            src-tauri/**/Cargo.lock
            flake.lock
            devenv.lock
            .github/workflows/nix-build.yml

  build:
    needs: detect-changes
    if: needs.detect-changes.outputs.nix-changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: nixbuild/nix-quick-install-action@v34
      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 2G
          gc-max-store-size-macos: 2G
          purge: false
      - name: Run nix build
        run: nix build
